salario = float(input('Informe o salário'))
salariore = (salario/100*5) + salario
inss = (salariore/100*11)
fgts = (salariore/100*8)
salfin = salariore-inss-fgts
if(salariore <= 1903.98):
    print(f'Salario inicial: {salario:.2f}')
    print(f'Salario reajustado: {salariore:.2f}')
    print(f'Desconto 11% INSS: {inss:.2f}')
    print(f'Desconto 8% FGTS: {fgts:.2f}')
    print('Desconto IR : 0.00')
    print(f'Total descontos INSS + FGTS + IR:{inss+fgts:.2f}')
    print(f'Salario final: {salfin:.2f}')
elif(salariore >= 1903.98 and salariore <= 2826.65):
    print(f'Salario inicial: {salario:.2f}')
    print(f'Salario reajustado: {salariore:.2f}')
    print(f'Desconto 11% INSS: {inss:.2f}')
    print(f'Desconto 8% FGTS: {fgts:.2f}')
    print(f'Desconto IR : {salariore/100*7.5:.2f}')
    print(f'Total descontos INSS + FGTS + IR:{inss+fgts+(salariore/100*7.5):.2f}')
    print(f'Salario final: {salfin -(salariore/100*7.5):.2f}')
elif(salariore >= 2826.65 and salariore <= 3751.05 ):
    print(f'Salario inicial: {salario:.2f}')
    print(f'Salario reajustado: {salariore:.2f}')
    print(f'Desconto 11% INSS: {inss:.2f}')
    print(f'Desconto 8% FGTS: {fgts:.2f}')
    print(f'Desconto IR : {salariore/100*15:.2f}')
    print(f'Total descontos INSS + FGTS + IR:{inss+fgts+(salariore/100*15):.2f}')
    print(f'Salario final: {salfin -(salariore/100*15):.2f}')
elif(salariore >= 3751.05 and salariore <= 4664.68 ):
    print(f'Salario inicial: {salario:.2f}')
    print(f'Salario reajustado: {salariore:.2f}')
    print(f'Desconto 11% INSS: {inss:.2f}')
    print(f'Desconto 8% FGTS: {fgts:.2f}')
    print(f'Desconto IR : {salariore/100*22.5:.2f}')
    print(f'Total descontos INSS + FGTS + IR:{inss+fgts+(salariore/100*22.5):.2f}')
    print(f'Salario final: {salfin -(salariore/100*22.5):.2f}')
elif(salariore > 4664.68):
    print(f'Salario inicial: {salario:.2f}')
    print(f'Salario reajustado: {salariore:.2f}')
    print(f'Desconto 11% INSS: {inss:.2f}')
    print(f'Desconto 8% FGTS: {fgts:.2f}')
    print(f'Desconto IR : {salariore/100*27.5:.2f}')
    print(f'Total descontos INSS + FGTS + IR:{inss+fgts+(salariore/100*27.5):.2f}')
    print(f'Salario final: {salfin -(salariore/100*27.5):.2f}')
